name: Python-Package-Structure
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    # container: docker://dvcorg/cml-py3:latest
    strategy:
      matrix:
        python-version: [3.9, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
     #    python -m pip install --upgrade pip
     #    pip install -r requirements.txt

      - name: run-tests
        run: |
     #      python -m unittest
          
      - name: run_analysis
        run: |
      #    python ./scripts/overview_to_satisfaction.py

